### ISSUE TITLE
Spécifier aérodrome avec activité planeur

### ISSUE THREAD

**Issue by mlep** [vmath54/xcsoar#1]
Les fichiers cup permettent de préciser les aérodromes avec une activité planeur (valeur 4 pour le champ 7 (= waypoint style). 
Suggestion : si le mot planeur apparaît dans le pdf de la carte VAC, utiliser la valeur 4.

**Comment by vmath54** [comment]
Merci pour la suggestion. 

La valeur 4 ( GliderSite) semble intéressante pour des terrains n'ayant que planeur comme activité ; je ne suis donc pas partisan de mettre cette valeur si le mon 'planeur' apparait dans le PDF de la carte VAC.
J'ai quand même interrogé le chef pilote de mon club, qui est également de cet avis.
